In [14]:
list1=[1,2,3,4]   # Array of elements stored in square brackets
list1             # is a heterogenius

[1, 2, 3, 4]

In [22]:
list2=['a','b','c','d']
list2

['a', 'b', 'c', 'd']

In [21]:
list3=['a',1,2,3,'c']
list3

['a', 1, 2, 3, 'c']

In [20]:
list4=['a',1,'apple',10.4,10+5j]
list4

['a', 1, 'apple', 10.4, (10+5j)]

In [19]:
list5=[100,100]   # elements can be accepted
list5

[100, 100]

In [24]:
l1=["how are you","Hi hello"]
l1

['how are you', 'Hi hello']

In [26]:
l2=[1,2,['a','b','c'],3,4]
l2

[1, 2, ['a', 'b', 'c'], 3, 4]

In [27]:
type(l1)

list

In [28]:
l10=[1,2,10,6,7,4,9]

In [30]:
type(l10)

list

In [31]:
len(l10)

7

In [32]:
max(l10)

10

In [33]:
min(l10)

1

In [35]:
type(l10),len(l10),max(l10),min(l10),sum(l10)

(list, 7, 10, 1, 39)

In [36]:
l11=[1,2,3,'A','B']
sum(l11)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [37]:
l12=[1,2,3,[4,5,6]]
sum(l12)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [40]:
sum('a','b')

TypeError: sum() can't sum strings [use ''.join(seq) instead]

In [41]:
l1=[1,2,3,4]
l2=['A','B',"C",'D']

In [43]:
l1+l2

[1, 2, 3, 4, 'A', 'B', 'C', 'D']

In [44]:
l1-l2

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [45]:
l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

In [46]:
l1/l2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [47]:
l1*2

[1, 2, 3, 4, 1, 2, 3, 4]

in

In [48]:
l2

['A', 'B', 'C', 'D']

In [49]:
'A' in l2

True

In [50]:
'AA' in l2

False

In [52]:
for i in l2:
    print(i)

A
B
C
D


In [70]:
i=0
while i<len(l2):
    print("The Positive index of",l2[i],"is",i)
    i+=1

The Positive index of A is 0
The Positive index of B is 1
The Positive index of C is 2
The Positive index of D is 3


In [69]:
for i in range(len(l2)):
    print("The Positive index of",l2[i],"is",i)

The Positive index of A is 0
The Positive index of B is 1
The Positive index of C is 2
The Positive index of D is 3


In [73]:
i=0
while i<len(l2):
    print("The Negative index of",l2[i],"is",i-len(l2))
    i+=1

The Negative index of A is -4
The Negative index of B is -3
The Negative index of C is -2
The Negative index of D is -1


In [74]:
for i in range(len(l2)):
    print("The Negative index of",l2[i],"is",i-len(l2))

The Negative index of A is -4
The Negative index of B is -3
The Negative index of C is -2
The Negative index of D is -1


In [75]:
l2[3]='Mobin'
l2

['A', 'B', 'C', 'Mobin']

In [76]:
l1=[[[[[1,2,3,4]]]]]

In [98]:
l1[0][0][0][0][3]

4

In [99]:
len(l1)

1

In [100]:
l2=[[[[['A','B',[1,2,3,['Cherry']]]]]]]

In [109]:
l2[0][0][0][0][2][3]

['Cherry']

In [110]:
l3=[[[[['A','B',[1,2,3,['Cherry']]]]]]]

In [113]:
l3[0][0][0][0][2][3][0]

'Cherry'

In [112]:
len(l3)

1

In [115]:
l1=[[1,2,3]]
for i in l1[0]:
    print(i)

1
2
3


In [116]:
str(5)+'Mobin'

'5Mobin'

In [118]:
"I said"+("hay"*2)+"Hey!"

'I saidhayhayHey!'

In [119]:
"The"+2

TypeError: can only concatenate str (not "int") to str

In [120]:
True+False

1

In [121]:
string=input("Enter the String:")
position=eval(input("Enter at which location need to change the character"))
character=input("Enter the Character")
string[position]='k'
print(string)

Enter the String:My Name Is Mobin
Enter at which location need to change the character5
Enter the Characterk


TypeError: 'str' object does not support item assignment

In [125]:
string='abracadabra'
string[:5]+'k'+string[6:]

'abrackdabra'

In [126]:
def mutate_string(string, position, character):
    return string[:5]+'k'+string[6:]

In [127]:
mutate_string('abracadabra',5,'k')

'abrackdabra'

In [128]:
string=input("Enter the String")
position,character=eval(input("Eter the Position")),input("Enter Character")
string[:5]+"k"+string[6:]

Enter the Stringabracadabra
Eter the Position5
Enter Characterk


'abrackdabra'

In [130]:
string='abracadabra'
string_out=''
for i in range(len(string)):
    if i==5:
        string_out+='k'
    else:
        string_out+=string[i]
print(string_out)

abrackdabra


In [131]:
l1=[1,2,3,4,5,6,7,8,9]

In [132]:
l1[0:4]

[1, 2, 3, 4]

In [133]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

In [134]:
downstairs=areas[:6]
downstairs

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]

In [136]:
upstairs=areas[6:]
upstairs

['bedroom', 10.75, 'bathroom', 9.5]

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

In [165]:
l1=[1,2,3,4]

In [166]:
l1=l1+[5]
l1

[1, 2, 3, 4, 5]

In [167]:
del(l1[-3]);del(l1[-2])

In [168]:
l1

[1, 2, 5]

In [170]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)
print(areas_copy)

[5.0, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


In [178]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [179]:
l1=[7,6,9,10,1,2,7]

In [182]:
sorted(l1,reverse=True)

[10, 9, 7, 7, 6, 2, 1]

In [190]:
import string
l1='swimming pool'
upper(l1)

NameError: name 'upper' is not defined

In [191]:
l1.upper()

'SWIMMING POOL'

In [192]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
for i in range(len(areas)):
    if areas[i]==20.0:
        print(i)

2


In [193]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

2


In [196]:
# Create list areas
areas = [11.25, 18.0, 20.0,9.50, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))


# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
2


In [201]:
areas.reverse()

In [199]:
l1

In [204]:
import math
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [205]:
# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in=np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m=np_height_in*0.0254

# Print np_height_m
print(np_height_m)

NameError: name 'height_in' is not defined

In [206]:
import numpy as np

In [207]:
np.array([True,1,2,3,4,False])

array([1, 1, 2, 3, 4, 0])

In [208]:
np.array([4,3,0])+np.array([0,2,2])

array([4, 5, 2])

In [209]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])